# используем язык java. Travis CI поддерживает другие языки тоже.
language: java

jdk:
  - openjdk13

before_install:
  - chmod +x gradlew

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту veshousis1@gmail.com если сборка упала
notifications:
  email:
    recipients:
      -veshousis1@gmail.com
    on_success: never # default: change
    on_failure: always # default: always

env:
  global:
    - CODECOV_TOKEN="b6441ab4-f8f8-4d4c-8254-345a6464cfd0"
